### ISSUE TITLE
pskc:secret

### ISSUE THREAD

**Issue by laulaufer** [arthurdejong/python-pskc#3]
Hello,
nice tool, i can play with it. works well except on key'svalue.

in the file i don't have secret defined like this
pskc:Secret
pskc:PlainValuexxxxxxxxxxxxxxxxx/pskc:PlainValue,

but
        pskc:Secret
          pskc:EncryptedValue
            <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc" />
            xenc:CipherData
              xenc:CipherValuetl7+c85vvvvvvvvvvvvvxMfPvg20ypjGBj/Q/UFihpJpEcccccccccccQD/xenc:CipherValue
            /xenc:CipherData
          /pskc:EncryptedValue
          pskc:ValueMACGEzcOEaavasFkccccccccccccKfP3aM=/pskc:ValueMAC
        /pskc:Secret

and then it can not provide any information .. and you cannot create xml file like this.

Laurent

**Comment by arthurdejong** [comment]
Can you provide an XML file to illustrate what you mean? The Github comment got messed up a bit.

Are you trying to read an existing PSKC file or do you want to create one?

**Comment by laulaufer** [comment]
Hello Arthur,
Sorry i was not available....
yes it is an existing PSKC file. please find an example attached.
Regards,
Laurent

**Comment by arthurdejong** [comment]
I think Github dropped your attachment. I think Github requires you put it in a zip file but also feel free to email it to me privately.

**Comment by arthurdejong** [comment]
Closing this issue for now. Feel free to re-open or open a new issue with any parsing issues you may have.
