### ISSUE TITLE
Invalid XML Passing Tests

### ISSUE THREAD

**Issue by ememisya** [arthurdejong/python-pskc#4]
This may be low priority of course but I've noticed the *.pskcxml files under test packages are not valid per schema described in https://tools.ietf.org/html/rfc6030#section-11 [`<xs:attribute name="Id" type="xs:string" use="required"/>`], it may be useful to let the users know that the key container they received was not built based on the RFC.

**Comment by arthurdejong** [comment]
Thanks. I have been working on supporting a wider range of PSKC variations that are found in the wild. This means accepting various files that don't follow the schema. I would like the library to be conservative in what to send and be liberal in what to accept. As such it doesn't do schema validation and accepts a lot of stuff that does not validate the schema.

I think the Git version only has a few cases in which it can generate a PSKC file that does not conform to the schema (you can leave out the id and you now can have zero or more than one pskc:Key per pskc:KeyPackage).

I would welcome patches for having a mechanism to get parsing warnings when parsing a non-conformant PSKC file or improvements that would avoid writing invalid PSKC files.

**Comment by arthurdejong** [comment]
Closing this because nobody came forward to do the work for this. If anyone is interested in extra validation, feel free to re-open.
